before_script:
  - module load astrocyte
  - module load python/3.6.1-2-anaconda
  - pip install --user pytest-pythonpath==0.7.1 pytest-cov==2.5.1
  - module load nextflow/0.31.1_Ignite
  - mkdir test_data/hu.v3s1r500
  - mkdir test_data/mu.v3s1r500
  - mkdir test_data/hu.v3s2r10k
  - mkdir test_data/mu.v3s2r10k
  - mkdir test_data/hu.v2s2r10k
  - ln -sfn /project/shared/bicf_workflow_ref/workflow_testdata/cellranger/cellranger_count/hu.v3s1r500/* test_data/hu.v3s1r500/
  - ln -sfn /project/shared/bicf_workflow_ref/workflow_testdata/cellranger/cellranger_count/mu.v3s1r500/* test_data/mu.v3s1r500/
  - ln -sfn /project/shared/bicf_workflow_ref/workflow_testdata/cellranger/cellranger_count/hu.v3s2r10k/* test_data/hu.v3s2r10k/
  - ln -sfn /project/shared/bicf_workflow_ref/workflow_testdata/cellranger/cellranger_count/mu.v3s2r10k/* test_data/mu.v3s2r10k/
  - ln -sfn /project/shared/bicf_workflow_ref/workflow_testdata/cellranger/cellranger_count/hu.v2s2r10k/* test_data/hu.v2s2r10k/

stages:
  - astrocyte
  - simple
  - detailed

astrocyte_check:
  stage: astrocyte
  script:
    - astrocyte_cli check ../cellranger_count
  artifacts:
    expire_in: 2 days
  retry:
    max: 1
    when:
      - always

simple_1:
  stage: simple
  only:
    - branches
    - tags
  except:
    - develop
    - master
  script:
  - nextflow run workflow/main.nf --fastq "$CI_PROJECT_DIR/test_data/hu.v3s1r500/*.fastq.gz" --designFile "$CI_PROJECT_DIR/test_data/hu.v3s1r500/design.csv" --genome 'GRCh38-3.0.0' --kitVersion 'three' --version '3.0.2'
  - pytest -m count302
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - .nextflow.log
    expire_in: 2 days
  retry:
    max: 1
    when:
      - always

simple_2:
  stage: simple
  only:
    - branches
  except:
    - develop
    - master
    - tags
  script:
  - nextflow run workflow/main.nf --fastq "$CI_PROJECT_DIR/test_data/mu.v3s1r500/*.fastq.gz" --designFile "$CI_PROJECT_DIR/test_data/mu.v3s1r500/design.csv" --genome 'mm10-3.0.0' --kitVersion 'three' --version '3.0.1'
  - pytest -m count301
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - .nextflow.log
    expire_in: 2 days
  retry:
    max: 1
    when:
      - always

detailed_1:
  stage: detailed
  only:
    - develop
    - master
  except:
    - tags
  script:
  - nextflow run workflow/main.nf --fastq "$CI_PROJECT_DIR/test_data/hu.v3s2r10k/*.fastq.gz" --designFile "$CI_PROJECT_DIR/test_data/hu.v3s2r10k/design.csv" --genome 'GRCh38-3.0.0' --kitVersion 'auto' --version '3.0.2'
  - pytest -m count302
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - .nextflow.log
    expire_in: 2 days
  retry:
    max: 1
    when:
      - always

detailed_2:
  stage: detailed
  only:
    - develop
    - master
  except:
    - tags
  script:
  - nextflow run workflow/main.nf --fastq "$CI_PROJECT_DIR/test_data/mu.v3s2r10k/*.fastq.gz" --designFile "$CI_PROJECT_DIR/test_data/mu.v3s2r10k/design.csv" --genome 'mm10-3.0.0' --kitVersion 'three' --version '3.0.2'
  - pytest -m count302
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - .nextflow.log
    expire_in: 2 days
  retry:
    max: 1
    when:
      - always

detailed_3:
  stage: detailed
  only:
    - develop
    - master
  except:
    - tags
  script:
  - nextflow run workflow/main.nf --fastq "$CI_PROJECT_DIR/test_data/hu.v2s2r10k/*.fastq.gz" --designFile "$CI_PROJECT_DIR/test_data/hu.v2s2r10k/design.csv" --genome 'GRCh38-1.2.0' --kitVersion 'two' --version '2.1.1'
  - pytest -m count211
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - .nextflow.log
    expire_in: 2 days
  retry:
    max: 1
    when:
      - always

