before_script:
  - module load astrocyte
  - module load python/3.6.1-2-anaconda
  - pip install --user pytest-pythonpath==0.7.1 pytest-cov==2.5.1
  - module load nextflow/19.09.0
  - mkdir test_data/hu.v3s1r500
  - mkdir test_data/mu.v3s1r500
  - mkdir test_data/hu.v3s2r10k
  - mkdir test_data/mu.v3s2r10k
  - mkdir test_data/hu.v2s2r10k
  - ln -sfn /project/shared/bicf_workflow_ref/workflow_testdata/cellranger/cellranger_count/hu.v3s1r500/* test_data/hu.v3s1r500/
  - ln -sfn /project/shared/bicf_workflow_ref/workflow_testdata/cellranger/cellranger_count/mu.v3s1r500/* test_data/mu.v3s1r500/
  - ln -sfn /project/shared/bicf_workflow_ref/workflow_testdata/cellranger/cellranger_count/hu.v3s2r10k/* test_data/hu.v3s2r10k/
  - ln -sfn /project/shared/bicf_workflow_ref/workflow_testdata/cellranger/cellranger_count/mu.v3s2r10k/* test_data/mu.v3s2r10k/
  - ln -sfn /project/shared/bicf_workflow_ref/workflow_testdata/cellranger/cellranger_count/hu.v2s2r10k/* test_data/hu.v2s2r10k/

stages:
  - astrocyte
  - simple
  - detailed

astrocyte_check:
  stage: astrocyte
  script:
    - astrocyte_cli check ../cellranger_count
  artifacts:
    expire_in: 2 days
  retry:
    max: 1
    when:
      - always

simple_1:
  stage: simple
  only:
    - branches
    - tags
  except:
    refs:
      - develop
      - master
  script:
  - nextflow run workflow/main.nf --fastq "test_data/hu.v3s1r500/*.fastq.gz" --designFile "test_data/hu.v3s1r500/design.csv" --genome 'GRCh38-3.0.0' --kitVersion 'three' --version '3.1.0' -with-tower
  - pytest -m count310
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - .nextflow.log
      - workflow/output/count310/sample1/outs/web_summary.html
      - workflow/output/multiqc/run/multiqc_report.html
    expire_in: 2 days
  retry:
    max: 1
    when:
      - always

simple_2:
  stage: simple
  only:
    - branches
  except:
    refs:
      - develop
      - master
      - tags
  script:
  - nextflow run workflow/main.nf --fastq "test_data/mu.v3s1r500/*.fastq.gz" --designFile "test_data/mu.v3s1r500/design.csv" --genome 'mm10-3.0.0' --kitVersion 'three' --version '3.1.0' -with-tower
  - pytest -m count310
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - .nextflow.log
      - workflow/output/count310/sample1/outs/web_summary.html
      - workflow/output/multiqc/run/multiqc_report.html
    expire_in: 2 days
  retry:
    max: 1
    when:
      - always

detailed_1:
  stage: detailed
  only:
    - develop
    - master
  except:
    refs:
      - tags
  script:
  - nextflow run workflow/main.nf --fastq "test_data/hu.v3s2r10k/*.fastq.gz" --designFile "test_data/hu.v3s2r10k/design.csv" --genome 'GRCh38-3.0.0' --kitVersion 'auto' --version '3.1.0' -with-tower
  - pytest -m count310
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - .nextflow.log
      - workflow/output/count310/sample1/outs/web_summary.html
      - workflow/output/multiqc/run/multiqc_report.html
    expire_in: 2 days
  retry:
    max: 1
    when:
      - always


detailed_2:
  stage: detailed
  only:
    - develop
    - master
  except:
    refs:
      - tags
  script:
  - nextflow run workflow/main.nf --fastq "test_data/hu.v3s2r10k/*.fastq.gz" --designFile "test_data/hu.v3s2r10k/design.csv" --genome 'GRCh38-3.0.0' --kitVersion 'auto' --version '3.0.2' -with-tower
  - pytest -m count302
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - .nextflow.log
      - workflow/output/count302/sample1/outs/web_summary.html
      - workflow/output/multiqc/run/multiqc_report.html
    expire_in: 2 days
  retry:
    max: 1
    when:
      - always

detailed_3:
  stage: detailed
  only:
    - develop
    - master
  except:
    refs:
      - tags
  script:
  - nextflow run workflow/main.nf --fastq "test_data/mu.v3s2r10k/*.fastq.gz" --designFile "test_data/mu.v3s2r10k/design.csv" --genome 'mm10-3.0.0' --kitVersion 'three' --version '3.0.1' -with-tower
  - pytest -m count301
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - .nextflow.log
      - workflow/output/count301/sample1/outs/web_summary.html
      - workflow/output/multiqc/run/multiqc_report.html
    expire_in: 2 days
  retry:
    max: 1
    when:
      - always

detailed_4:
  stage: detailed
  only:
    - develop
    - master
  except:
    refs:
      - tags
  script:
  - nextflow run workflow/main.nf --fastq "test_data/hu.v2s2r10k/*.fastq.gz" --designFile "test_data/hu.v2s2r10k/design.csv" --genome 'GRCh38-1.2.0' --kitVersion 'two' --version '2.1.1' -with-tower
  - pytest -m count211
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - .nextflow.log
      - workflow/output/count211/sample1/outs/web_summary.html
      - workflow/output/multiqc/run/multiqc_report.html
    expire_in: 2 days
  retry:
    max: 1
    when:
      - always
